---
- name: check services
  hosts: all
  tasks:
    - name: running services
      ansible.builtin.service:
        state: started
        name: "{{ item }}"
      loop:
        - httpd
        - sshd